### ISSUE TITLE
Bug in mega-story-dalle & tokenizer

### ISSUE THREAD

**Issue by julkaztwittera** [adymaharana/storydalle#11]
Hi,
I am trying to train the mega-dalle version, but there is one bug in the dataloader, e.g. in `flintstones_dataloader.py` in line 160 there is:
```
tokens.append(self.tokenizer.encode(text.lower()))
```
while the TextTokenizer has no encode function. I changed it for tokenize and modified slightly as follows:
```
t = self.tokenizer.tokenize(text.lower())
if len(t) > 64: 
    t = t[:64]
t = t[1:(len(t)-1)]
t += [0]*(64-len(t))
tokens.append(t)
```
Now there is no error, but I wonder wether this is the way it was supposed to be.

**Comment by KyonP** [comment]
it also happens with Pororo data

**Comment by KyonP** [comment]
Maybe it has a version difference with the author's local code.

I hope this gets fixed.

```
Training:   0%|                                        | 0/1273 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/root/anaconda3/envs/ldm/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/root/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/my/storydalle/mega-story-dalle/pororo_dataloader.py", line 201, in __getitem__
    tokens = self.tokenizer.encode(caption.lower())
AttributeError: 'TextTokenizer' object has no attribute 'encode'
```
